dolbyio-samples/rts-app-react-publisher-viewer

.storybook/main.ts, apps/stories/src/Input.stories.tsx, libs/input/.eslintrc.json, libs/input/jest.config.ts, libs/input/project.json, libs/input/src/index.tsx, libs/input/src/types.ts, libs/input/src/vite-env.d.ts, libs/input/tsconfig.json, libs/input/tsconfig.lib.json, libs/input/tsconfig.spec.json, tsconfig.base.json
Issue: https://github.com/dolbyio-samples/rts-app-react-publisher-viewer/issues/214
Created dark-mode text input as per [Figma](https://www.figma.com/file/MyQjNaOOvrMcNLDpCQOxxi/Dolby.io-%2F-Product-Apps%C2%A0%E2%80%93-Components?node-id=26%3A4125&t=hkydTsshlV9IdX28-0), for use in https://github.com/dolbyio-samples/rts-app-react-publisher-viewer/pull/206
=> Issue 214 text input component

.github/workflows/ci-cd.yml, apps/e2e-test/scripts/auto_utils.sh, apps/e2e-test/scripts/launch_server.sh
Fix viewer invite URL
[Viewer app base url for deployment preview of pull request](https://github.com/dolbyio-samples/rts-app-react-publisher-viewer/issues/220)
=> Fix viewer invite URL

apps/e2e-test/src/hooks/ScenarioWorld.ts, apps/e2e-test/src/hooks/hooks.ts, apps/e2e-test/src/playwright-support/utils/BrowserManager.ts, apps/e2e-test/src/steps/app-specific/navigation.step.ts, apps/e2e-test/src/utils/types.ts, apps/e2e-test/test.config.ts
Make test config independent of any tool.
=> Issue 230 E2E Test: Test Config independent of tool

.github/workflows/ci-cd.yml, apps/publisher/src/app.tsx, libs/device-selection/src/index.tsx, libs/dolbyio-theme/src/index.ts, libs/dolbyio-theme/src/styles/Modal.ts, libs/use-multi-media-devices/src/index.ts
- Added camera preview when user wants to add a new camera source
- Refined CI-CD workflow to cancel previous run when there is new commit
=> Issue 194 add camera popover

apps/publisher/src/app.tsx, apps/publisher/src/components/publisher-video-view/index.tsx, apps/publisher/src/components/publisher-video-view/types.ts
Solved issue #294 
@vishalkharge  do we have this BDD scenario? If not, we should add one for this case.
=> only show close button for each source when there are more than 1 sources

libs/use-viewer/src/reducer.ts
=> show video or audio statistics

libs/use-viewer/src/index.ts, libs/use-viewer/src/utils.ts
=> [Bugfix] Viewer video freeze after remove publisher source

apps/viewer/src/app.tsx, libs/use-viewer/src/index.ts, libs/use-viewer/src/types.ts, libs/use-viewer/src/utils.ts
#284 
- Update quality options from layer
- Reset quality if old option isn't in new options list
Fix involved reprojecting before reselecting, otherwise it did not work
=> Issue 284 video in viewer freezes with large bitrate resolution changes in publisher

libs/statistics-popover/src/index.tsx
=> [Bugfix] Issue 285 filter invalid statistics

libs/use-multi-media-streams/src/index.ts
Solved #319 
Handling camera/microphone connect/disconnect is out of scope, we could do it in next version.
=> [Bugfix] remove device change event handler

apps/viewer/src/app.tsx, libs/use-viewer/src/index.ts, libs/use-viewer/src/reducer.ts, libs/use-viewer/src/types.ts, libs/use-viewer/src/utils.ts
=> Issue 326 stream stats in viewer regression

libs/use-viewer/src/index.ts
#335 
This dispatch does nothing and is no longer defined.
=> Issue 335 removed deprecated dispatch in useViewer

.github/actions/setup/action.yml, .github/workflows/ci-cd.yml, .github/workflows/test-suite.yml, apps/e2e-test/features/multisource.feature, apps/e2e-test/features/publisher-camera-stream.feature, apps/e2e-test/features/publisher-local-file-stream.feature, apps/e2e-test/features/publisher-screen-stream.feature, apps/e2e-test/project.json, apps/e2e-test/src/hooks/ScenarioWorld.ts, apps/publisher/project.json
- Created parallel test jobs
Solves #343
=> Issue 343 Github - Execute Test Jobs In Parallel 

.github/workflows/ci-cd.yml
=> Always deploy the publisher and viewer

apps/viewer/src/app.tsx, package.json, yarn.lock
solved #284 and #248
**Note: user has to wait for 2~3 seconds for video restore from frozen state.**
=> solved #284 and #248

libs/use-multi-media-streams/src/utils.ts, libs/use-publisher/src/index.ts, libs/use-viewer/src/index.ts
=> Issue 353 viewer issues when source name empty

apps/viewer/src/app.tsx
=> Issue 349 delayed rerendering when changing quality in viewer

apps/publisher/src/components/publisher-video-view/types.ts, apps/publisher/src/components/publisher-video-view/video-control-bar/types.ts, apps/viewer/src/components/viewer-video-view/types.ts, apps/viewer/src/components/viewer-video-view/video-control-bar/types.ts, libs/statistics-popover/src/components/statistics-info/index.tsx, libs/statistics-popover/src/components/statistics-info/types.ts, libs/statistics-popover/src/components/statistics-info/utils.ts, libs/statistics-popover/src/index.tsx, libs/statistics-popover/src/types.ts, libs/use-publisher/src/index.ts, libs/use-publisher/src/types.ts, libs/use-viewer/src/index.ts, libs/use-viewer/src/types.ts, libs/video-view/src/types.ts, millicast-sdk.d.ts, package.json, yarn.lock
#367, #238
New issue: doesn't support quality limitation reason stat field
=> Issue 367 implement dolby webrtc statistics library

apps/viewer/src/app.tsx, libs/use-page-close-prompt/src/index.ts, libs/use-publisher/src/constants.ts
This PR addresses one bug and one improvement:
Improvement:
- added a new bitrate option for 4Mbps
- https://github.com/dolbyio-samples/rts-app-react-publisher-viewer/issues/391 
Bug:
- fixed missing warning message when page is closed for Firefox and Safari
- https://github.com/dolbyio-samples/rts-app-react-publisher-viewer/issues/175
=> Improvement and bug

apps/e2e-test/features/publisher-camera-stream.feature, apps/e2e-test/features/publisher-local-file-stream.feature, apps/e2e-test/features/publisher-screen-stream.feature, apps/viewer/src/app.tsx, apps/viewer/src/components/viewer-video-tiles/video-tile/video-control-bar/settings-popover/settings-popover.tsx, apps/viewer/src/components/viewer-video-tiles/video-tile/video-control-bar/settings-popover/types.ts, apps/viewer/src/components/viewer-video-tiles/viewer-video-tiles.tsx, apps/viewer/src/utils.ts, libs/dolbyio-icons/src/Sliders.tsx, libs/dolbyio-icons/src/index.ts
- added Sliders icon
- move query param handling logic to a hook
- added source selection item to settings menu
=> Multiview source selection
